### ISSUE TITLE
Metodi da implementare

### ISSUE THREAD

**Issue by alegotta** [Fs00/rpg-game-4inc#5]
## PERSONAGGIO:
- [x] ritirata (vedi #12)
- [x] calcolo probabilità contrattacco
- [x] calcolo danni
- [x] toString()
- [x] stampa messaggi relativi alla fuga
- [x] stampa messaggi relativi al colpo subito

## DEBOLE:
- [x] implementazione completata

## CONTADINO:
- [x] implementazione interfaccia IAttaccante
- [x] stampa messaggi relativi all'attacco/contrattacco

## COMBATTENTE:
- [x] implementazione interfaccia IAttaccante (URGENTE! Compito di @AlibabaSakura)
- [x] stampa messaggi relativi all'attacco/contrattacco

## SOLDATO:
- [x] implementazione interfaccia IDifesa (compito di @alegotta - vedi #11)
- [x] stampa messaggi relativi al guard

## CLASSE DI GESTIONE PARTITA: (compito di @AlibabaSakura)
- [x] controlloPartitaConclusa()
- [x] faiMossa()

## MAIN A RIGA DI COMANDO:
- [x] implementazione in corso a cura di @Fs00

## IATTACCANTE:
- [x] **preparaAttacco()** _(Il personaggio perde un turno per sferrare un attacco potenziato)_
- [x] **attacca(Personaggio dest)** (vedi #10)
- [x] **contrattacca(Personaggio p)** (vedi #7)

Se ve ne viene in mente qualcun'altro, aggiungetelo modificando il post!

**Comment by Fs00** [comment]
Importante: ora bisogna implementare la stampa dei messaggi relativi agli attacchi/contrattacchi/guard ecc. nelle varie classi, utilizzando il metodo statico _stampaMessaggio_ di GestionePartita. Puoi farlo tu, @AlibabaSakura? (vedi il post sopra per le classi in cui va fatto)

**Comment by Fs00** [comment]
Lavoro completato, quindi per il momento chiudo.
